# This script:
# - Reads tables generated by 4_reporting_manuscript/3_models.R
# - Generates a .docx supplemental table document

# setup --------------------------------------------------------------------

library(flextable)
library(officer)
library(tidyverse)

# Project functions:

source("src/functions.R")

# Define flextable defaults:

set_flextable_defaults(
  font.family = "Times New Roman",
  table.layout = "autofit",
  split = FALSE,
  caption.style = "Table Caption",
  caption.align = "left"
)

# Supplemental-table spacing and BMP wrapping:

bmp_wrap_width <- 35
body_row_height <- 0.35

format_supplemental_bmp <-
  function(.bmp) {
    .bmp %>%
      format_bmp() %>%
      str_wrap(width = bmp_wrap_width)
  }

set_supplemental_row_height <-
  function(.table) {
    .table %>%
      set_table_properties(
        layout = "autofit",
        width = 1
      ) %>%
      height_all(
        height = body_row_height,
        part = "body"
      ) %>%
      hrule(
        rule = "atleast",
        part = "body"
      )
  }

supplemental_section <-
  prop_section(
    page_size = page_size(orient = "portrait"),
    page_margins =
      page_mar(
        top = 1,
        bottom = 1,
        left = 1,
        right = 1
      )
  )

# Read tables:

list.files(
  "output/tables",
  pattern = "^table",
  full.names = TRUE
) %>% 
  set_names(
    basename(.) %>% 
      tools::file_path_sans_ext()
  ) %>% 
  map(
    ~ read_csv(.x)
  ) %>% 
  list2env(.GlobalEnv)

# Define sample-size columns:

sample_size_columns <-
  c(
    K = "k",
    Studies = "n_studies"
  )

# Define posterior columns:

posterior_columns <-
  c(
    "estimate",
    "lcl",
    "ucl",
    "prob_positive",
    "excludes_zero"
  )

# table s1 species richness -----------------------------------------------

richness_flextable <-
  table_species_richness_by_bmp %>%
  
  # Print the practice names:
  
  mutate(
    BMP = format_supplemental_bmp(bmp),
    .keep = "unused"
  ) %>%
  select(
    BMP,
    all_of(sample_size_columns),
    all_of(posterior_columns)
  ) %>%
  
  # Format and caption:
  
  format_manuscript_table(
    .caption =
      as_paragraph(
        as_b("Table S1"),
        ". Pooled effect of each best management practice on species ",
        "richness, from a Bayesian multilevel meta-analysis. Effect sizes are ",
        "Hedges' g; positive values indicate a better conservation outcome ",
        "under the practice. K is the number of effect sizes and Studies the ",
        "number of independent studies contributing to each estimate. ",
        "Bold indicates a 95% credible interval that excludes zero."
      )
  ) %>%
  set_supplemental_row_height()

# table s2 pooled abundance -----------------------------------------------

pooled_abundance_flextable <-
  table_bmp_cells %>% 
  filter(
    response_metric == "abundance",
    guild == "all_grassland"
  ) %>% 
  
  # By-guild rows first:
  
  arrange(
    desc(estimate)
  ) %>%
  
  # Print the practice names:
  
  mutate(
    BMP = format_supplemental_bmp(bmp),
    .keep = "unused"
  ) %>%
  select(
    BMP,
    all_of(sample_size_columns),
    all_of(posterior_columns)
  ) %>% 
  
  # Format and caption:
  
  format_manuscript_table(
    .caption =
      as_paragraph(
        as_b("Table S2"),
        ". Effect of best management practices on abundance pooled across",
        " species. Effect sizes are reported as Hedges' ",
        as_i("g"),
        ". Positive values indicate a better conservation outcome under the ",
        "practice. ",
        "Bold indicates a 95% credible interval that excludes zero. "
      )
  ) %>%
  set_supplemental_row_height()

# table s3 abundance by guild ---------------------------------------------

guild_abundance_flextable <-
  table_bmp_cells %>% 
  filter(
    response_metric == "abundance",
    guild != "all_grassland"
  ) %>% 
  
  # By-guild rows first:
  
  arrange(
    guild,
    desc(estimate)
  ) %>%
  
  # Print the practice names:
  
  mutate(
    BMP = format_supplemental_bmp(bmp),
    guild = 
      guild %>% 
      str_remove("_grassland") %>% 
      str_to_title(),
    .keep = "unused"
  ) %>%
  select(
    Guild = guild,
    BMP,
    all_of(sample_size_columns),
    all_of(posterior_columns)
  ) %>% 
  
  # Format and caption:
  
  format_manuscript_table(
    .caption =
      as_paragraph(
        as_b("Table S3"),
        ". Effect of best management practices on abundance by grassland ",
        "guild. Effect sizes are reported as Hedges' ",
        as_i("g"),
        ". Positive values indicate a better conservation outcome under the ",
        "practice. ",
        "Bold indicates a 95% credible interval that excludes zero. "
      )
  ) %>%
  
  # Merge guilds:
  
  merge_v(j = ~ Guild) %>% 
  hline(
    i = ~
      !duplicated(Guild, fromLast = TRUE),
    border = 
      fp_border_default(width = 0.5)
  ) %>%
  set_supplemental_row_height()

# table s4 guild contrasts ------------------------------------------------

contrasts_flextable <-
  table_guild_contrasts %>%
  
  # No species richness (reported in the text):
  
  filter(response_metric != "nest_success") %>% 
  
  
  # Strongest effect first, within response:
  
  arrange(
    desc(estimate)
  ) %>%
  
  # Print the display names:
  
  mutate(
    Response = format_response(response_metric),
    BMP = format_supplemental_bmp(bmp),
    prob_positive = prob_a_greater
  ) %>%
  select(
    BMP,
    all_of(posterior_columns)
  ) %>%
  
  # Format and caption:
  
  format_manuscript_table(
    .caption =
      as_paragraph(
        as_b("Table S4"),
        ". Direct posterior contrasts between obligate and facultative ",
        "grassland birds within each practice, on the scale of the metric ",
        "concerned: Hedges' ",
        as_i("g"),
        ". A positive contrast means the practice benefits obligate species ",
        "more than facultative species; the final column is the posterior ",
        "probability of that. ",
        "Bold indicates a 95% credible interval that excludes zero. "
      )
  ) %>%
  
  # Rename the posterior columns:
  
  set_header_labels(
    `Hedges' g (95% CrI)` = "obligate – facultative (95% CrI)",
    `P(> 0)` = "P(obligate > facultative)"
  ) %>%
  set_supplemental_row_height()

# Tables in document order:

manuscript_tables <-
  list(
    species_richness = richness_flextable,
    abundance_pooled = pooled_abundance_flextable,
    abundance_by_guild = guild_abundance_flextable,
    guild_contrasts = contrasts_flextable
  )

# The table the document opens on:

opening_table <- "species_richness"

# One page per table:

manuscript_document <-
  manuscript_tables %>%
  discard_at(opening_table) %>%
  reduce(
    \(.document, .table) {
      .document %>%
        body_add_break() %>%
        body_add_flextable(.table)
    },
    .init =
      read_docx() %>%
      body_add_flextable(
        pluck(manuscript_tables, opening_table)
      )
  ) %>%
  body_set_default_section(
    value = supplemental_section
  )

# Write to file:

print(
  manuscript_document,
  target = "output/tables/supplemental_tables.docx"
)

# clear the environment ----------------------------------------------------

rm(
  list = ls()
)
